### ISSUE TITLE
How to train a model with case information

### ISSUE THREAD

**Issue by sriram-c** [stanfordnlp/GloVe#105]
Hi,

I want to train the corpus with case information (not converting to lowercase).
I can't find any options in the  build/glove for this.
I can see there is a pretrained model available at this link with cased information.

Common Crawl (840B tokens, 2.2M vocab, cased, 300d vectors, 2.03 GB download): glove.840B.300d.zi

Please help me in training a cased model.

Thanks,
sriram

**Comment by akanshajainn** [comment]
give your corpus input where each token separated by a space, it works regardless of case type of words.
