### ISSUE TITLE
Inconsistent results for same set of parameters in different iteration

### ISSUE THREAD

**Issue by MuhammadZeeshan34** [stanfordnlp/GloVe#112]
I have been trying to find out a way to set its seed level to reproduce the same results but unfortunately, it is producing different results in each iteration. Does anyone know how can I tune it to get the same results for the same set of parameters? Thanks

**Comment by AngledLuffa** [comment]
glove.c now has a -seed parameter which you can use.  (Thanks to @mebrunet)
