### ISSUE TITLE
TypeError: object of type 'map' has no len()

### ISSUE THREAD

**Issue by 1234567890-qwertyuiop** [stanfordnlp/GloVe#132]
```
iter: 001, cost: 0.069002
iter: 002, cost: 0.051681
iter: 003, cost: 0.046146
iter: 004, cost: 0.043024
iter: 005, cost: 0.041181
iter: 006, cost: 0.039970
iter: 007, cost: 0.039106
iter: 008, cost: 0.038448
iter: 009, cost: 0.037929
iter: 010, cost: 0.037509
iter: 011, cost: 0.037160
iter: 012, cost: 0.036864
iter: 013, cost: 0.036608
iter: 014, cost: 0.036387
iter: 015, cost: 0.036193
$ python eval/python/evaluate.py
Traceback (most recent call last):
  File "eval/python/evaluate.py", line 110, in <module>
    main()
  File "eval/python/evaluate.py", line 22, in main
    vector_dim = len(vectors[ivocab[0]])
TypeError: object of type 'map' has no len()
```

Any suggestions on how to resolve this issue?

**Comment by npeirson** [comment]
have you converted from map to list?  
```
list_of_map = list(vectors[ivocab[0]])
vector_dim = len(list_of_map)
```

**Comment by 1234567890-qwertyuiop** [comment]
> have you converted from map to list?
> 
> ```
> list_of_map = list(vectors[ivocab[0]])
> vector_dim = len(list_of_map)
> ```

Thanks! It's strange that the example code does not contain the list_of_map variable name

**Comment by LavenderMP** [comment]
I got same issue when runing ./demo.sh file

**Comment by dzf0023** [comment]
i got same issue when training my own corpus,

**Comment by dzf0023** [comment]
> have you converted from map to list?
> 
> ```
> list_of_map = list(vectors[ivocab[0]])
> vector_dim = len(list_of_map)
> ```

this gives me another issue:
  File "eval/python/evaluate.py", line 31, in main
    for word, v in vectors.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by AngledLuffa** [comment]
It shouldn't be necessary to convert anything.  `dict` absolutely has the
ability to call `len()` on it.  What version python are you using?

**Comment by blmoistawinde** [comment]
Same problem with python3.6, seems an issue with python version compatability

replace eval/python/evaluate.py with this one https://github.com/stanfordnlp/GloVe/pull/122 solved my problem

**Comment by AngledLuffa** [comment]
Do you have any further information you can share?  Perhaps a data file on which this is happening?

**Comment by AngledLuffa** [comment]
This honestly makes no sense.  This has been true for a long time:

```
>>> len({})
0
```

There is an underlying issue which needs to be fixed.  The patch referenced is hiding the error rather than actually fixing it.  

If someone can provide a data file which reproduces it, that would be great.

**Comment by AngledLuffa** [comment]
Wait a second.  Are people using an older version of the code?  The current evaluate.py doesn't have map() in it anywhere.  Maybe that's where the confusion arises.

**Comment by AngledLuffa** [comment]
Figured it out.  This issue was present in 1.2, but has been fixed in the git source.  Anyone else who comes across this, please make sure to update.
