### ISSUE TITLE
vocab_count doesn't work if no option is given

### ISSUE THREAD

**Issue by kmkurn** [stanfordnlp/GloVe#137]
https://github.com/stanfordnlp/GloVe/blob/07d59d5e6584e27ec758080bba8b51fce30f69d8/src/vocab_count.c#L242

This line in `vocab_count.c` makes the program stop working and print usage info when no option is given, e.g. `vocab_count < corpus.txt > vocab.txt`. Since all options are optional, this command should work and use the default options instead. This is a minor issue which can be handled by providing at least one option (e.g. `-verbose 2`). Nevertheless, it'd be nice if optional arguments are truly optional.

**Comment by AngledLuffa** [comment]
Good point.  Fixed
