### ISSUE TITLE
Ability to read pre-trained embeddings into R

### ISSUE THREAD

**Issue by Drew2019** [stanfordnlp/GloVe#143]
Working in R, I was wondering whether anyone has read in the pre-trained embeddings (e.g., "glove.6B.50d.txt") into that system. I've had zero luck reading this text file into R so that the product is the word embedding matrix of words by vector, and have some unfamiliarity with the txt file formatting. Has anyone successfully done this, either pulling from a saved .txt file or from the site itself, and if so how was that text converted to a matrix in R?

**Comment by AngledLuffa** [comment]
The text format is just word followed by a list of numbers, in this case 50.  I don't know any R but I have to imagine that isn't hard to read.
