### ISSUE TITLE
running off-the-shelf demo errs

### ISSUE THREAD

**Issue by monajalal** [stanfordnlp/GloVe#148]
(base) tw-mbp-mjalal:glove mjalal$ cd GloVe-1.2 && make
mkdir -p build
gcc src/glove.c -o build/glove -lm -pthread -Ofast -march=native -funroll-loops -Wno-unused-result
gcc src/shuffle.c -o build/shuffle -lm -pthread -Ofast -march=native -funroll-loops -Wno-unused-result
gcc src/cooccur.c -o build/cooccur -lm -pthread -Ofast -march=native -funroll-loops -Wno-unused-result
gcc src/vocab_count.c -o build/vocab_count -lm -pthread -Ofast -march=native -funroll-loops -Wno-unused-result
(base) tw-mbp-mjalal:GloVe-1.2 mjalal$ ./demo.sh
mkdir -p build
gcc src/glove.c -o build/glove -lm -pthread -Ofast -march=native -funroll-loops -Wno-unused-result
gcc src/shuffle.c -o build/shuffle -lm -pthread -Ofast -march=native -funroll-loops -Wno-unused-result
gcc src/cooccur.c -o build/cooccur -lm -pthread -Ofast -march=native -funroll-loops -Wno-unused-result
gcc src/vocab_count.c -o build/vocab_count -lm -pthread -Ofast -march=native -funroll-loops -Wno-unused-result
--2019-07-03 15:03:15--  http://mattmahoney.net/dc/text8.zip
Resolving mattmahoney.net (mattmahoney.net)... 67.195.197.75
Connecting to mattmahoney.net (mattmahoney.net)|67.195.197.75|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31344016 (30M) [application/zip]
Saving to: ‘text8.zip’

text8.zip                             100%[========================================================================>]  29.89M  1.25MB/s    in 24s     

2019-07-03 15:03:40 (1.23 MB/s) - ‘text8.zip’ saved [31344016/31344016]

Archive:  text8.zip
  inflating: text8                   
BUILDING VOCABULARY
Processed 17005207 tokens.
Counted 253854 unique words.
Truncating vocabulary at min count 5.
Using vocabulary of size 71290.

COUNTING COOCCURRENCES
window size: 15
context: symmetric
max product: 13752509
overflow length: 38028356
Reading vocab from file "vocab.txt"...loaded 71290 words.
Building lookup table...table contains 94990279 elements.
Processed 17005206 tokens.
Writing cooccurrences to disk.........2 files in total.
Merging cooccurrence files: processed 60666466 lines.

SHUFFLING COOCCURRENCES
array size: 255013683
Shuffling by chunks: processed 60666466 lines.
Wrote 1 temporary file(s).
Merging temp files: processed 60666466 lines.

TRAINING MODEL
Read 60666466 lines.
Initializing parameters...done.
vector size: 50
vocab size: 71290
x_max: 10.000000
alpha: 0.750000
iter: 001, cost: 0.068991
iter: 002, cost: 0.051679
iter: 003, cost: 0.046140
iter: 004, cost: 0.043019
iter: 005, cost: 0.041187
iter: 006, cost: 0.039974
iter: 007, cost: 0.039112
iter: 008, cost: 0.038458
iter: 009, cost: 0.037941
iter: 010, cost: 0.037520
iter: 011, cost: 0.037170
iter: 012, cost: 0.036879
iter: 013, cost: 0.036616
iter: 014, cost: 0.036395
iter: 015, cost: 0.036201
Traceback (most recent call last):
  File "eval/python/evaluate.py", line 110, in <module>
    main()
  File "eval/python/evaluate.py", line 22, in main
    vector_dim = len(vectors[ivocab[0]])
TypeError: object of type 'map' has no len()
(base) tw-mbp-mjalal:GloVe-1.2 mjalal$

**Comment by BlagaVic** [comment]
Same issue here

**Comment by AngledLuffa** [comment]
This is fixed in the current master branch.
