### ISSUE TITLE
glove.twitter.27B.25d, item 38522

### ISSUE THREAD

**Issue by Yueshen666** [stanfordnlp/GloVe#159]
item 38522 : token "0.065581" ohly has 24 dimensions in 'glove.twitter.27B.25d.txt'

**Comment by AngledLuffa** [comment]
can you give us access to the training data you used?

**Comment by Yueshen666** [comment]
sorry. I mean the pre-trained vectors in glove.twitter.27B.25d.txt (from: http://nlp.stanford.edu/data/glove.twitter.27B.zip) in which the glove vector for token "0.065581" only has 24 dimensions ( should be 25).

**Comment by pengowray** [comment]
The entry name is the control character "NEL" (0x85; Next Line) followed by 25 numbers.

```
 0.065581 0.39605 -0.96669 0.23706 -0.41379 -0.97006 0.16601 -1.292 -0.58989 0.11632 -1.365 -0.27939 -0.57222 -0.97108 -0.56319 -0.015263 -0.70465 -0.13867 1.0702 -0.25557 0.25122 -0.87755 0.70999 0.9118 -0.30077
```
