### ISSUE TITLE
Typo mistake

### ISSUE THREAD

**Issue by Genie-Liu** [stanfordnlp/GloVe#176]
While I am looking into the source code, I find out there's a typo mistake which may cause null point exception if malloc fail. 
The if statement should check `W_updates2` instead of `W_updates1`. I have created a PR to fix it. https://github.com/stanfordnlp/GloVe/pull/175

https://github.com/stanfordnlp/GloVe/blob/afd83fbf62b676d339c93639af1312b1b7626b53/src/glove.c#L174-L178

**Comment by AngledLuffa** [comment]
Excellent, thanks!
