### ISSUE TITLE
Word missing

### ISSUE THREAD

**Issue by Qi-HuT** [stanfordnlp/GloVe#182]
I use golve to train my own corpus. I'm only here demo.sh Changes made to the document.
![image](https://user-images.githubusercontent.com/46215418/92478515-d4b32780-f214-11ea-9bda-9fda05fe12aa.png)
but Final vectors.txt Some words are missing from the file.

**Comment by AngledLuffa** [comment]
Are they rare words?  There is a VOCAB_MIN_COUNT field

Please don't use pictures to send debugging information.  Text is much
better.
