### ISSUE TITLE
Train glove on oscar dataset

### ISSUE THREAD

**Issue by rezasugiarto** [stanfordnlp/GloVe#186]
Hi, any guide for train glove from multiple source file (e.g. from oscar dataset)?

**Comment by AngledLuffa** [comment]
I don't know any of the specifics, but is it not possible to simply merge
the files?

**Comment by rezasugiarto** [comment]
Hi, i can't merge all files. Also, I think we can't do train glove using generator right? Since we need to calculate co-occurrence on whole corpus.

**Comment by AngledLuffa** [comment]
The fundamental problem is there's only one input file in the glove code,
AFAIK.
