### ISSUE TITLE
Download link for glove vectors not working

### ISSUE THREAD

**Issue by luffycodes** [stanfordnlp/GloVe#187]
Access forbidden for urls (https://nlp.stanford.edu/data/wordvec/glove.840B.300d.zip) to download pre-trained vectors.

**Comment by AngledLuffa** [comment]
Where are you finding that link?  All of the links under "Download
pre-trained word vectors" work for me.

**Comment by luffycodes** [comment]
Yeah, they are working for me now.. thanks
