### ISSUE TITLE
Does GloVe support the Spanish language?

### ISSUE THREAD

**Issue by zekaouinoureddine** [stanfordnlp/GloVe#188]
I'm working on a project, and **`my dataset is in Spanish`**, and wanted to test GloVe too to see how my model will behave based on different pre-trained embeddings?

**Comment by AngledLuffa** [comment]
People have used GloVe to build embeddings for many different languages,
but we haven't build Spanish embeddings ourselves

**Comment by zekaouinoureddine** [comment]
Okay! Thanks for the quick reply
