### ISSUE TITLE
a bug in the update loop in glove.c?

### ISSUE THREAD

**Issue by ktrapeznikov** [stanfordnlp/GloVe#19]
perhaps a bug or clever regularization in lines 133 and 134? Are l1 and l2 supposed to be switched?
```    C++
        /* Adaptive gradient updates */
        fdiff *= eta; // for ease in calculating gradient
        real W_updates1_sum = 0;
        real W_updates2_sum = 0;
        for (b = 0; b < vector_size; b++) {
            // learning rate times gradient for word vectors
            temp1 = fdiff * W[b + l2];
            temp2 = fdiff * W[b + l1];
            // adaptive updates
            W_updates1[b] = temp1 / sqrt(gradsq[b + l1]);
            W_updates2[b] = temp2 / sqrt(gradsq[b + l2]);
            W_updates1_sum += W_updates1[b];
            W_updates2_sum += W_updates2[b];
            gradsq[b + l1] += temp1 * temp1;
            gradsq[b + l2] += temp2 * temp2;
        }
```

**Comment by Russell91** [comment]
Interesting indeed. If it is a bug it's been there for over a year without being noticed - the old tar gz from last february had these lines as well: https://web.archive.org/web/20150209031512/http://www-nlp.stanford.edu/software/glove.tar.gz. The best thing to do is try switching and see if the accuracy improves!

**Comment by Russell91** [comment]
It seems that the code is intentional. Interesting observation though.

**Comment by ktrapeznikov** [comment]
yeah this makes sense, its just chain rule.... 
 d f(a^T b) /da = b*f'(a^Tb) and d f(a^T b) /db = a*f'(a^T b)
