### ISSUE TITLE
Source data for training embedding glove.840B.300d 

### ISSUE THREAD

**Issue by lfoppiano** [stanfordnlp/GloVe#190]
Dear all, 
   I'm collecting information about various embedding approaches and I'm looking for information about how you did perform the training the embeddings: `Common Crawl (840B tokens, 2.2M vocab, cased, 300d vectors, 2.03 GB download): glove.840B.300d.zip``

The [paper](https://nlp.stanford.edu/pubs/glove.pdf) does not discuss them indeed. 

In particular, I'm interested in: 
 - would you have the exact source data that was used? Which version of Common Crawls? 
 - were such embeddings trained only with English text or did you mix it with other languages? 

Thank you in advance

**Comment by AngledLuffa** [comment]
The intent was English only, although other things may have snuck in.  I
don't think we have records on which version of Common Crawl, unfortunately.

**Comment by lfoppiano** [comment]
Thank you

**Comment by lfoppiano** [comment]
I have another question, do you have, by any chance, the command's parameters that were used to train these embeddings?

**Comment by AngledLuffa** [comment]
I'm sorry, but the person who did the original training is long gone and
didn't leave behind any notes.

**Comment by lfoppiano** [comment]
Thanks
