### ISSUE TITLE
Broken links of pre-trained models 

### ISSUE THREAD

**Issue by brleandro** [stanfordnlp/GloVe#194]
The links to download the pre-trained vectors are broken.

**Comment by AngledLuffa** [comment]
They work fine for me.  If you're using Chrome, you need to copy the link
into a new tab.

**Comment by SageAgastya** [comment]
Same issue @AngledLuffa , I can't download pretrained embeddings. 
It says "nginx 1.10.3, 404 NOT FOUND".
I have tried it in chrome, safari and using wget as well but it appears as if the link is broken.

**Comment by brleandro** [comment]
It works with firefox.

**Comment by SageAgastya** [comment]
So what to do if I am working on remote instance, if wget is failing to download this file?

**Comment by AngledLuffa** [comment]
Currently our cluster is hosed and nothing is downloading.  Please check
back in a couple hours

**Comment by brleandro** [comment]
I just tried and I couldn't download it. I downloaded last week. The server should be down.

**Comment by AngledLuffa** [comment]
Should be back now

**Comment by Levis0045** [comment]
It still down for me
