### ISSUE TITLE
About Document Boundary

### ISSUE THREAD

**Issue by OlafLee** [stanfordnlp/GloVe#20]
When I saw the code of coocurrence.c, I found that it doesn't detect the boundary between documents. So if I train the model with context from both sides, I may use the begginning of the next document. Do you think that is a problem or doesn't matter? One solution to that I think is to set an x_min which means we discard occasional coocurrence of words.

**Comment by Russell91** [comment]
My intuition is that this would not make a large difference. For shorter documents there would be more potential benefit. If there was a simple way to implement it in the code, and it improved performance on the benchmark task, we could consider it.

**Comment by manning** [comment]
I also would strongly suspect that this just doesn't matter much - though I can see how it could be a bit prettier to stop when moving to text that is completely unrelated.

**Comment by Russell91** [comment]
I'm going to close this down. Please feel free to open it back up if you try out the changes and see some improvements!

**Comment by OlafLee** [comment]
@Russell91 OK.Thank you. I'll inform you if I make a further trial.

**Comment by OlafLee** [comment]
@manning Thank you for your opinion professor.
