### ISSUE TITLE
what is the meaning of '.' in glove pretrained vector?

### ISSUE THREAD

**Issue by BodyCSoulN** [stanfordnlp/GloVe#203]
Hi, thanks for your great job!
I have downloaded the `glove.840b.300d.txt`. and i found that there are some '.' in the vector, what is meaning of it? Zero?
![image](https://user-images.githubusercontent.com/40445446/155444229-93ac5c6d-37d8-45bb-a3e1-cbf37479a72c.png)

**Comment by AngledLuffa** [comment]
you mean in the text or in the numbers?  what's an example?

**Comment by BodyCSoulN** [comment]
> you mean in the text or in the numbers? what's an example?

As you can see in the figure, there are two '.' in line 52344, what is the meaning of it?

**Comment by AngledLuffa** [comment]
Ah... is it possible this is a tokenization issue?  Each column should have 301 entries, I believe, 1 word and 300 numbers.  In this case, do you now have multiple "word" entries followed by 300 numbers?

**Comment by BodyCSoulN** [comment]
Oh, I am sorry. I left out the previous word and now one line represents a 300-dimensional vector. My question is: why does a '.' appear where a number should appear?

**Comment by AngledLuffa** [comment]
No idea, honestly.  If it's now lined up correctly with 300 numbers at the
end of each line, you're saying one of them is just "." instead of a number?

**Comment by BodyCSoulN** [comment]
I am so sorry bro.It is my fault.
I found that the length of this line is 303.
And this line starts with three '.'
![image](https://user-images.githubusercontent.com/40445446/155475343-7c807be3-80e8-40b8-ae5f-dc08404bb522.png)

Thanks a lot for your patient answer!

So what's meaning of three '.' in the picture.

**Comment by AngledLuffa** [comment]
Thanks for following up!
