### ISSUE TITLE
Why is binary the default format?

### ISSUE THREAD

**Issue by DavidNemeskey** [stanfordnlp/GloVe#21]
According to the usage page of the _glove_ program,
```
-binary <int>
        Save output in binary format (0: text, 1: binary, 2: both); default 0
```

If 0 is text, and the default is 0, doesn't it mean that the default output should be text? However, I ran the program without specifying anything for binary, and ended up with binary output.

**Comment by DavidNemeskey** [comment]
Oh, BTW:
```
int use_binary = 1;
```

**Comment by kmkurn** [comment]
I had this problem recently. Why was this issue closed? I think the usage should be updated to say that the default is 1.
