### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by hamza13-12** [stanfordnlp/GloVe#222]
Currently, the download link is not working. 

!wget http://nlp.stanford.edu/data/glove.6B.zip

This gives connection timed out after a few seconds. What's the solution?

**Comment by AngledLuffa** [comment]
Thanks for the alert.  We'll look into it, and in the meantime, there are
mirrors of the data files on HF:

https://huggingface.co/stanfordnlp/glove/tree/main

**Comment by AngledLuffa** [comment]
Thanks, I reported that to our devops team

**Comment by AngledLuffa** [comment]
Should work now!
