### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Avitella** [stanfordnlp/GloVe#23]
https://github.com/stanfordnlp/GloVe/blob/master/src/glove.c#L288

It's looks like memory leak here

**Comment by Avitella** [comment]
And maybe here:
https://github.com/stanfordnlp/GloVe/blob/master/src/glove.c#L280
https://github.com/stanfordnlp/GloVe/blob/master/src/glove.c#L281

**Comment by Russell91** [comment]
Yea, the one in the for loop is worth fixing. The others are fairly benign, but I fixed them and a few others in the pull request
