### ISSUE TITLE
ValueError in evaluate.py

### ISSUE THREAD

**Issue by filannim** [stanfordnlp/GloVe#27]
```
bash-4.1$ sh demo.sh
		Binary input file of shuffled cooccurrence data (produced by 'cooccur' and 'shuffle'); default cooccurrence.shuf.bin
	-vocab-file <file>
		File containing vocabulary (truncated unigram counts, produced by 'vocab_count'); default vocab.txt

SHUFFLING COOCCURRENCES
array size: 4080218931
Shuffling by chunks: processed 174462388 lines.
Wrote 1 temporary file(s).
Merging temp files: processed 174462388 lines.

TRAINING MODEL
Read 174462388 lines.
Initializing parameters...done.
vector size: 100
vocab size: 231387
x_max: 10.000000
alpha: 0.750000
iter: 001, cost: 0.138845
iter: 002, cost: 0.093234
iter: 003, cost: 0.082903
iter: 004, cost: 0.077870
iter: 005, cost: 0.074741
iter: 006, cost: 0.072627
iter: 007, cost: 0.070986
iter: 008, cost: 0.069763
iter: 009, cost: 0.068730
iter: 010, cost: 0.067894
iter: 011, cost: 0.067183
iter: 012, cost: 0.066559
iter: 013, cost: 0.066034
iter: 014, cost: 0.065546
iter: 015, cost: 0.065127
Traceback (most recent call last):
  File "eval/python/evaluate.py", line 110, in <module>
    main()
  File "eval/python/evaluate.py", line 33, in main
    evaluate_vectors(W_norm, vocab, ivocab)
  File "eval/python/evaluate.py", line 66, in evaluate_vectors
    ind1, ind2, ind3, ind4 = indices.T
ValueError: need more than 0 values to unpack
```

In demo.sh I've updated ONLY the following lines:
```
MEMORY=64.0
VECTOR_SIZE=100
NUM_THREADS=24
```

Any idea of what may be the problem?

Thanks,
michele.

**Comment by gsh199449** [comment]
@filannim I have the same problem with you. How did you fix it?

**Comment by Russell91** [comment]
@gsh199449 what did you do to produce the error? Did you run demo.sh?

**Comment by gsh199449** [comment]
@Russell91 I have solve this problem. I train the model use my own corpus, but the eval data use the QA corpus, and my data doesn't contain this words. In the latest version, the demo.sh contains this `if [ "$CORPUS" = 'text8' ]; then` to avoid this problem.

**Comment by kkarthikvk** [comment]
> ```
> bash-4.1$ sh demo.sh
>         Binary input file of shuffled cooccurrence data (produced by 'cooccur' and 'shuffle'); default cooccurrence.shuf.bin
>     -vocab-file <file>
>         File containing vocabulary (truncated unigram counts, produced by 'vocab_count'); default vocab.txt
> 
> SHUFFLING COOCCURRENCES
> array size: 4080218931
> Shuffling by chunks: processed 174462388 lines.
> Wrote 1 temporary file(s).
> Merging temp files: processed 174462388 lines.
> 
> TRAINING MODEL
> Read 174462388 lines.
> Initializing parameters...done.
> vector size: 100
> vocab size: 231387
> x_max: 10.000000
> alpha: 0.750000
> iter: 001, cost: 0.138845
> iter: 002, cost: 0.093234
> iter: 003, cost: 0.082903
> iter: 004, cost: 0.077870
> iter: 005, cost: 0.074741
> iter: 006, cost: 0.072627
> iter: 007, cost: 0.070986
> iter: 008, cost: 0.069763
> iter: 009, cost: 0.068730
> iter: 010, cost: 0.067894
> iter: 011, cost: 0.067183
> iter: 012, cost: 0.066559
> iter: 013, cost: 0.066034
> iter: 014, cost: 0.065546
> iter: 015, cost: 0.065127
> Traceback (most recent call last):
>   File "eval/python/evaluate.py", line 110, in <module>
>     main()
>   File "eval/python/evaluate.py", line 33, in main
>     evaluate_vectors(W_norm, vocab, ivocab)
>   File "eval/python/evaluate.py", line 66, in evaluate_vectors
>     ind1, ind2, ind3, ind4 = indices.T
> ValueError: need more than 0 values to unpack
> ```
> 
> In demo.sh I've updated ONLY the following lines:
> 


Have you found the solution for this problem ?

**Comment by AngledLuffa** [comment]
If you are having a problem, please first try the current git head.  If that doesn't work, please do your best to explain what the problem is.

**Comment by hyunjaecho94** [comment]
I ran into the same problem. I am training the model using my own corpus. I replaced text8 to corpus.txt (my corpus file) at lines 18 and 48 of demo.sh.

It seems to train successfully until I run into this problem: `ValueError: not enough values to unpack (expected 4, got 0)` Any idea why this is occurring?

```
vector size: 50
vocab size: 187228
x_max: 10.000000
alpha: 0.750000

04/02/20 - 09:31.33PM, iter: 001, cost: 0.032667
04/02/20 - 09:31.34PM, iter: 002, cost: 0.026803
04/02/20 - 09:31.35PM, iter: 003, cost: 0.026545
04/02/20 - 09:31.37PM, iter: 004, cost: 0.026292
04/02/20 - 09:31.38PM, iter: 005, cost: 0.026078
04/02/20 - 09:31.39PM, iter: 006, cost: 0.025895
04/02/20 - 09:31.41PM, iter: 007, cost: 0.025736
04/02/20 - 09:31.42PM, iter: 008, cost: 0.025597
04/02/20 - 09:31.43PM, iter: 009, cost: 0.025474
04/02/20 - 09:31.45PM, iter: 010, cost: 0.025364
04/02/20 - 09:31.46PM, iter: 011, cost: 0.025265
04/02/20 - 09:31.47PM, iter: 012, cost: 0.025174
04/02/20 - 09:31.49PM, iter: 013, cost: 0.025091
04/02/20 - 09:31.50PM, iter: 014, cost: 0.025016
04/02/20 - 09:31.51PM, iter: 015, cost: 0.024945
$ python eval/python/evaluate.py
Traceback (most recent call last):
  File "eval/python/evaluate.py", line 110, in <module>
    main()
  File "eval/python/evaluate.py", line 33, in main
    evaluate_vectors(W_norm, vocab, ivocab)
  File "eval/python/evaluate.py", line 66, in evaluate_vectors
    ind1, ind2, ind3, ind4 = indices.T
ValueError: not enough values to unpack (expected 4, got 0)
```

**Comment by AngledLuffa** [comment]
Can you share your data file with me?  I'll delete it when I'm done with
it, if you care about that kind of thing.

**Comment by hyunjaecho94** [comment]
@AngledLuffa 

My `corpus.txt` contains sentences, and every word in the file is in `vocab.txt` file along with its number. For example, 

`corpus.txt`
this is sentence one. Here is sentence two.

`vocab.txt`
this 1
is 2
sentence 3
one 4
here 5
two 6

**Comment by AngledLuffa** [comment]
I actually did find the issue with that description.  Sometimes an entire test file can be missing from the vocab, especially in two cases: training file too small, or training file has cased text, so Chicago is present instead of chicago from the eval.  I checked in a change which will hopefully fix that situation.

**Comment by AngledLuffa** [comment]
... and by "fix" I mean tell the user what happened and keep going rather than crash with a mysterious exception

**Comment by hyunjaecho94** [comment]
Thank you for the fix. Now I have a different problem.

Okay, I better be more specific with my data. Each "word" in my corpus is an ID that represents a "chunk" in my sequence of data. So, each word is not actual English word. My corpus looks like this: 

ID83 ID41 ID40 ID123 ID14 ID72 ID8 ID34 ID113 ID4 ID129 ID122 ID11. ID231 ID253 ID465 ID513 ID371 ID392 ID463 ID269 ID474 ID406 ID376 ID348 ID193 ID378 ID311 ID173 ID361 ID184 ID534 ID528. and so on...

As a result, my vocab.txt looks like this:
ID83 83
ID41 41
...


Maybe because of this, I get the following error:
```
vector size: 50
vocab size: 187228
x_max: 10.000000
alpha: 0.750000
04/04/20 - 12:16.46PM, iter: 001, cost: 0.032654
04/04/20 - 12:16.48PM, iter: 002, cost: 0.026804
04/04/20 - 12:16.49PM, iter: 003, cost: 0.026545
04/04/20 - 12:16.50PM, iter: 004, cost: 0.026292
04/04/20 - 12:16.51PM, iter: 005, cost: 0.026078
04/04/20 - 12:16.53PM, iter: 006, cost: 0.025895
04/04/20 - 12:16.54PM, iter: 007, cost: 0.025736
04/04/20 - 12:16.55PM, iter: 008, cost: 0.025597
04/04/20 - 12:16.57PM, iter: 009, cost: 0.025474
04/04/20 - 12:16.58PM, iter: 010, cost: 0.025364
04/04/20 - 12:16.59PM, iter: 011, cost: 0.025265
04/04/20 - 12:17.01PM, iter: 012, cost: 0.025174
04/04/20 - 12:17.02PM, iter: 013, cost: 0.025092
04/04/20 - 12:17.03PM, iter: 014, cost: 0.025016
04/04/20 - 12:17.05PM, iter: 015, cost: 0.024946
$ python eval/python/evaluate.py
ERROR: no lines of vocab kept for capital-common-countries.txt !
Example missing line: ['athens', 'greece', 'baghdad', 'iraq']
ERROR: no lines of vocab kept for capital-world.txt !
Example missing line: ['abuja', 'nigeria', 'accra', 'ghana']
ERROR: no lines of vocab kept for currency.txt !
Example missing line: ['algeria', 'dinar', 'angola', 'kwanza']
ERROR: no lines of vocab kept for city-in-state.txt !
Example missing line: ['chicago', 'illinois', 'houston', 'texas']
ERROR: no lines of vocab kept for family.txt !
Example missing line: ['boy', 'girl', 'brother', 'sister']
ERROR: no lines of vocab kept for gram1-adjective-to-adverb.txt !
Example missing line: ['amazing', 'amazingly', 'apparent', 'apparently']
ERROR: no lines of vocab kept for gram2-opposite.txt !
Example missing line: ['acceptable', 'unacceptable', 'aware', 'unaware']
ERROR: no lines of vocab kept for gram3-comparative.txt !
Example missing line: ['bad', 'worse', 'big', 'bigger']
ERROR: no lines of vocab kept for gram4-superlative.txt !
Example missing line: ['bad', 'worst', 'big', 'biggest']
ERROR: no lines of vocab kept for gram5-present-participle.txt !
Example missing line: ['code', 'coding', 'dance', 'dancing']
ERROR: no lines of vocab kept for gram6-nationality-adjective.txt !
Example missing line: ['albania', 'albanian', 'argentina', 'argentinean']
ERROR: no lines of vocab kept for gram7-past-tense.txt !
Example missing line: ['dancing', 'danced', 'decreasing', 'decreased']
ERROR: no lines of vocab kept for gram8-plural.txt !
Example missing line: ['banana', 'bananas', 'bird', 'birds']
ERROR: no lines of vocab kept for gram9-plural-verbs.txt !
Example missing line: ['decrease', 'decreases', 'describe', 'describes']
Questions seen/total: 0.00% (0/19544)
Traceback (most recent call last):
  File "eval/python/evaluate.py", line 115, in <module>
    main()
  File "eval/python/evaluate.py", line 33, in main
    evaluate_vectors(W_norm, vocab, ivocab)
  File "eval/python/evaluate.py", line 108, in evaluate_vectors
    (100 * correct_sem / float(count_sem), correct_sem, count_sem))
ZeroDivisionError: float division by zero
```

I think the error is due to the fact that my vocab is not comprised of valid English words, whereas the txt files above are. Therefore, `count_sem` is zero. Is that correct? How should I go around this?

**Comment by AngledLuffa** [comment]
Sounds like you should replace the included `evaluate.py` with a different
metric :)  `evaluate.py` is just intended to make sure things work, I
believe, rather than being a reliable score for how good the model is.
