### ISSUE TITLE
Fromat of the cooccur and shuffle output

### ISSUE THREAD

**Issue by armintabari** [stanfordnlp/GloVe#33]
I want to access the statistics before running the glove for dimension reduction to compare GloVe to other dimensionality reduction methods.

They are being saved in a binary file. How can I read the files and access the co-occurrence values?

**Comment by Russell91** [comment]
The files are written in series with the raw 12 byte c structure:
```
typedef struct cooccur_rec {
    int word1;
    int word2;
    real val;
} CREC;
```
in line 156 of https://github.com/stanfordnlp/GloVe/blob/master/src/cooccur.c. You'll either need to do some low level byte access or read them out in that format with a c program if you want to read them as is. Alternatively, you could modify the write_chunk file in coocur.c to write to an separate text file using printf, and analyze the contents directly.

**Comment by gullirg** [comment]
Hi, this was incredibly useful, thank you!

One thing I'd like to add is that the **16 bytes** format worked for me. 
Hope this can be useful to someone else.
