### ISSUE TITLE
\0 inside "big data" causes problem in vocab

### ISSUE THREAD

**Issue by chain** [stanfordnlp/GloVe#34]
When pasting together different data, there will be some garbage. If there are \0 bytes, then this will be included into vocab. Result is that vocab.txt will have one row with single column of data. This will cause the rest of the process to fail. 

Maybe add a check for \0 and discard it.

**Comment by Russell91** [comment]
Okay, sounds like a good find. If you're feeling generous, it would be great to get the solution as a pull request!

**Comment by chain** [comment]
Ok. I will do it as soon as possible.

**Comment by Russell91** [comment]
Can you describe this problem in a little more detail so that we can look into it?

**Comment by Russell91** [comment]
Please reopen this if you can describe the problem.
