### ISSUE TITLE
What is the real value returned by cooccur

### ISSUE THREAD

**Issue by armintabari** [stanfordnlp/GloVe#36]
Thank you for your fast responses.
I want to get the number of times each word cooccurred with other words.
In cooccur, is the "real val" in the struct "cooccur_rec" the count? If yes why is it double and not integer?

**Comment by Russell91** [comment]
Doubles can represent integers with perfect precision that are actually larger than a typical int32. See http://stackoverflow.com/questions/1848700/biggest-integer-that-can-be-stored-in-a-double.

**Comment by armintabari** [comment]
Thank you. So the values are the actual counts, and I should ignore the decimal part? Values in the output from cooccur is something like 45.3 and this means the count is 45?
