### ISSUE TITLE
raw_input not longer available in Python 3.X.X

### ISSUE THREAD

**Issue by kvillaville** [stanfordnlp/GloVe#39]
Hello guys, 

Please change raw_input() to input(), since it's not longer available in Python 3.X.X according to the documentation.

Link: https://docs.python.org/3/whatsnew/3.0.html

PEP 3111: raw_input() was renamed to input(). That is, the new input() function reads a line from sys.stdin and returns it with the trailing newline stripped. It raises EOFError if the input is terminated prematurely. To get the old behavior of input(), use eval(input()).

**Comment by kvillaville** [comment]
I'm going to create a fork and then do the pull request.

**Comment by Russell91** [comment]
Sure, if you're trying to add 2/3 compatibility though you might consider using six.moves.input(). [1]

https://pythonhosted.org/six/
