### ISSUE TITLE
vocab.txt and vector.txt

### ISSUE THREAD

**Issue by Tejaf** [stanfordnlp/GloVe#42]
I am having issue understanding where to get vocab.txt and vector.txt files. I am relatively new to this, please help. Thanks.

**Comment by Russell91** [comment]
Sure, let me first provide some high level info. Users who simply want some word vectors to use in a generic application can download pretrained word vectors as per the README. Users that eventually want to train on their own corpus are encouraged to first train on data that we provide as per the readme, so that they can go through the motions.

In the process on training on _our_ data, you'll generate vocab.txt and vector.txt. So if you follow the readme under https://github.com/stanfordnlp/GloVe#train-word-vectors-on-a-new-corpus, you should be set up!

**Comment by Tejaf** [comment]
@Russell91  Thank you for your response, however, like i said i am really new to NLP and ML, i fould a medium post which really interested me and i wanted to have it working as well `https://medium.com/lastmile-conversations/do-it-yourself-nlp-for-bot-developers-2e2da2817f3d#.97wc6ihcn` . Can you please go over my code because i am not getting the result he got. can you please share me some links that would really help me more as i am interested in building an AI aswell, and again, i am very new to this, i picked up machine learning on monday, this is my first test project, i really want it to work and i know i have a long way to go but i need lots of help. thank you. here is the code i ran;

```import numpy as np

vectors_file = '../data/glove.6B.50d.txt'
vocab_file = '../data/glove.6B.50d.txt'


class Embedding(object):

    def __init__(self, vocab_file, vectors_file):
        with open(vocab_file, 'r') as f:
            words = [x.rstrip().split(' ')[0] for x in f.readlines()]

        with open(vectors_file, 'r') as f:
            vectors = {}
            for line in f:
                vals = line.rstrip().split(' ')
                vectors[vals[0]] = [float(x) for x in vals[1:]]


        vocab_size = len(words)
        print vocab_size
        vocab = {w: idx for idx, w in enumerate(words)}
        ivocab = {idx: w for idx, w in enumerate(words)}

        vector_dim = len(vectors[ivocab[0]])
        print vector_dim
        W = np.zeros((vocab_size, vector_dim))
        for word, v in vectors.items():
            if word == '<unk>':
                continue
               
            W[vocab[word], :] = v

        # normalize each word vector to unit variance
        W_norm = np.zeros(W.shape)
        d = (np.sum(W ** 2, 1) ** (0.5))
        W_norm = (W.T / d).T
 

        self.W = W_norm
        self.vocab = vocab
        self.ivocab = ivocab

def find_similar_words(embed,text,refs,thresh):

    C = np.zeros((len(refs),embed.W.shape[1]))

    for idx, term in enumerate(refs):
        if term in embed.vocab:
            C[idx,:] = embed.W[embed.vocab[term], :]


    tokens = text.split(' ')
    scores = [0.] * len(tokens)
    found=[]

    for idx, term in enumerate(tokens):
        if term in embed.vocab:
            vec = embed.W[embed.vocab[term], :]
            cosines = np.dot(C,vec.T)
            score = np.mean(cosines)
            scores[idx] = score
            if (score > thresh):
                found.append(term)
    print scores

    return found
                

cuisine_refs = ["mexican","chinese","french","british","american"]
threshold = 0.2

text = "I want to find an indian restaurant"
 

embed = Embedding(vocab_file,vectors_file)
cuisines = find_similar_words(embed,text,cuisine_refs,threshold)
print(cuisines)```

when i ran it on a small dataset, although i didn't get my intended result but i didn't encoounter an error as well but when i ran it on this (glove.6B.50d.txt) file, i got this error  `C:\Users\new\Documents\Kudi\python\diy_nlp_bot.py:37: RuntimeWarning: invalid value encountered in divide
  W_norm = (W.T / d).T` along with the same incorrect answers.
 
 And i don't understand how this works d = (np.sum(W ** 2, 1) ** (0.5)) and what <unk> means in the if statement, i googled but didn't find much help.

Thank you Russell.

**Comment by Russell91** [comment]
Unfortunately, that's out of the scope of what we can do to help you. Best of luck!

**Comment by Tejaf** [comment]
Thanks.

**Comment by akshay-vaidya** [comment]
@Russell91 
Hi,
I am just trying to understand what vectors.txt and vocab.txt contain. First few records of vocab.txt file contain the following. 
the 1061396
of 593677
and 416629
one 411764
in 372201
a 325873

What does the number corresponding to each word mean?
What does 1061396 corresponding to the word 'the' mean? 

Thanks!

**Comment by drawar** [comment]
@akshay-vaidya : It's the count of occurrences of each (unique) word in the document.

**Comment by akshay-vaidya** [comment]
Thanks @drawar

**Comment by anurag1234567** [comment]
@akshay-vaidya ,@Russell91
Hi Akshay,

Could you please elaborate the steps for generating vocab.txt and vector.txt file on Windows.
I am unable to follow the steps describe on README.

Thanks
