### ISSUE TITLE
Gigaword5 license

### ISSUE THREAD

**Issue by rw** [stanfordnlp/GloVe#57]
According to https://catalog.ldc.upenn.edu/LDC2011T07, the Gigaword5 corpus is under a non-commercial license.

Does this 'pollute' the legal status of glove vectors derived from Gigaword5?

**Comment by Russell91** [comment]
IANAL, and so I cannot give you official advice here, but my observation has been that the weights of machine learning systems trained on data are not subject to the same license as the data itself. A large amount of thought was put into this surrounding the ImageNet competition, which you can look up. If you do consult a lawyer on this question, please update us below!
