### ISSUE TITLE
How to use or read the zip file?

### ISSUE THREAD

**Issue by guotong1988** [stanfordnlp/GloVe#91]
I have downloaded the `glove.840B.300d.zip`.
But I don't know how to read or use it.
Thank you..
@futurulus @gangeli @jtibshirani @manning @nihit @sebschu @vzhong

**Comment by vzhong** [comment]
Hi, please see here for an example on how to parse the zip file: https://github.com/vzhong/embeddings/blob/master/embeddings/glove.py

You can also use this library to load word embeddings: https://github.com/vzhong/embeddings
